# Generated by Django 4.1.1 on 2022-10-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='county',
            field=models.CharField(max_length=10),
        ),
    ]
